version: '3'

services:

  mariadb:
    image: mariadb:10.3.9
    container_name: url-shortener-mariadb
    ports:
      - '3306:3306'
    restart: 'on-failure'
    environment:
      MYSQL_DATABASE: url-shortener
      MYSQL_USER: url-admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ${PWD}